/** Human wording for audit/security action codes. Unknown codes fall back to a readable form of the code. */
const LABELS: Record<string, string> = {
  'account.created': 'Account created',
  'account.email_verified': 'Email address verified',
  'account.profile_updated': 'Profile updated',
  'account.photo_changed': 'Profile photo changed',
  'account.notification_preferences_changed': 'Notification preferences changed',
  'account.email_change_requested': 'Email change requested',
  'account.email_changed': 'Email address changed',
  'account.deactivated': 'Account deactivated',
  'auth.login': 'Signed in',
  'auth.login_failed': 'Failed sign-in attempt',
  'auth.login_locked': 'Account temporarily locked after failed attempts',
  'auth.logout': 'Signed out',
  'auth.password_changed': 'Password changed',
  'auth.password_reset_requested': 'Password reset requested',
  'auth.password_reset_completed': 'Password reset completed',
  'auth.sessions_revoked': 'Other devices signed out',
  'auth.session_revoked': 'A device was signed out',
  'auth.mfa_enabled': 'Two-factor authentication turned on',
  'auth.mfa_disabled': 'Two-factor authentication turned off',
  'auth.mfa_recovery_codes_regenerated': 'Recovery codes regenerated',
  'auth.mfa_challenge_failed': 'Failed two-factor code',
  'auth.mfa_recovery_code_used': 'Recovery code used',
  'auth.reauth_failed': 'Failed re-authentication',
  'business.created': 'Business created',
  'business.settings_changed': 'Business settings changed',
  'business.switched': 'Switched business',
  'business.ownership_transferred': 'Ownership transferred',
  'business.closed': 'Business closed',
  'business.mfa_requirement_changed': 'Two-factor requirement changed',
  'member.invited': 'Team member invited',
  'member.invite_revoked': 'Invitation revoked',
  'member.invite_resent': 'Invitation resent',
  'member.joined': 'Team member joined',
  'member.role_changed': 'Role changed',
  'member.suspended': 'Member suspended',
  'member.reactivated': 'Member reactivated',
  'member.removed': 'Member removed',
  'role.created': 'Role created',
  'role.permissions_changed': 'Role permissions changed',
  'role.archived': 'Role archived',
  'location.created': 'Location added',
  'location.updated': 'Location renamed',
  'location.archived': 'Location archived',
  'subscription.trial_started': 'Free trial started',
  'subscription.trial_expired': 'Free trial ended',
  'subscription.checkout_started': 'Checkout started',
  'subscription.changed': 'Subscription changed',
  'subscription.plan_changed': 'Plan changed',
  'subscription.downgrade_scheduled': 'Downgrade scheduled',
  'subscription.downgrade_cancelled': 'Scheduled downgrade cancelled',
  'subscription.cancelled': 'Subscription cancelled',
  'subscription.past_due': 'Payment overdue',
  'subscription.grace_period_started': 'Grace period started',
  'subscription.suspended': 'Subscription suspended',
  'subscription.expired': 'Subscription ended',
  'billing.payment_received': 'Payment received',
  'billing.payment_failed': 'Payment failed',
  'billing.invoice_issued': 'Invoice issued',
  'platform.custom_plan_assigned': 'Custom plan assigned by TFME',
  'data.export_requested': 'Data export requested',
  'data.exported': 'Data export ready',
  'data.export_downloaded': 'Data export downloaded',
  'customer.created': 'Customer added',
  'customer.updated': 'Customer updated',
  'customer.archived': 'Customer archived',
  'customer.restored': 'Customer restored',
  'file.uploaded': 'File uploaded',
  'file.archived': 'File removed',
};

export function eventLabel(action: string): string {
  return LABELS[action] ?? action.replace(/[._]/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}
