import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Alert, Badge, Card, PageHeader } from '@/components/ui';
import { DocumentActions } from '@/components/documents/DocumentActions';
import { StatusBadge, VisibilityBadge } from '@/components/documents/shared';
import { formatBytes, formatDate, formatDateTime } from '@/lib/format';
import { isAppError } from '@/lib/errors';
import { listCategories } from '@/server/files/categories';
import { RESOURCES } from '@/server/files/registry';
import { getFile } from '@/server/files/service';
import { requireBusiness } from '@/server/web/session';
import { recordHref } from '@/components/documents/record-links';

export const metadata: Metadata = { title: 'Document' };
export const dynamic = 'force-dynamic';

const SCAN: Record<string, string> = { CLEAN: 'Checked by a malware scanner', NOT_SCANNED: 'Basic safety checks only (no malware scanner is connected)', PENDING: 'Waiting to be scanned', FLAGGED: 'Flagged by the scanner' };

export default async function DocumentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const ctx = await requireBusiness();
  let d;
  try {
    d = await getFile(ctx, id);
  } catch (e) {
    if (isAppError(e) && (e.code === 'NOT_FOUND' || e.code === 'FORBIDDEN')) notFound();
    throw e;
  }
  const f = d.file;
  const cats = (await listCategories(ctx)).filter((c) => c.active || c.key === f.category).map((c) => ({ key: c.key, label: c.label }));
  const rule = f.resourceType ? RESOURCES[f.resourceType] : undefined;
  const can = (p: Parameters<typeof ctx.permissions.has>[0]) => ctx.permissions.has(p);
  const href = f.resourceType && f.resourceId ? recordHref(f.resourceType, f.resourceId) : null;
  const isImage = f.mimeType.startsWith('image/');
  const when = (x: Date) => formatDateTime(x, ctx.business.timezone, ctx.business.locale);

  return (
    <>
      <PageHeader
        title={f.name}
        description={`${d.categoryLabel} · ${formatBytes(f.sizeBytes)} · ${f.mimeType}`}
        actions={<Link href="/documents" className="inline-flex min-h-11 items-center text-sm text-brand-600 hover:underline md:min-h-10">All documents</Link>}
      />
      <div className="mb-3 flex flex-wrap gap-1.5"><VisibilityBadge v={f.visibility} /><StatusBadge status={f.status} />{f.source === 'GENERATED' && <Badge>Generated by TFME Auto</Badge>}{!f.isCurrent && <Badge tone="warn">Earlier version</Badge>}{f.isFinancial && <Badge tone="brand">Financial record</Badge>}</div>
      {f.status === 'TRASHED' && <div className="mb-3"><Alert tone="warn">This document is in the trash. It will be permanently deleted after the retention period unless it is restored.</Alert></div>}
      {!f.isCurrent && <div className="mb-3"><Alert tone="warn">A newer version of this document exists. This one is kept for the record.</Alert></div>}

      <div className="grid gap-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
        <div className="space-y-4">
          <Card>
            {isImage && d.can.download ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={`/api/v1/files/${f.id}`} alt={f.description ?? f.name} className="mx-auto max-h-[70vh] w-auto max-w-full rounded-lg" />
            ) : f.mimeType === 'application/pdf' && d.can.download ? (
              <div className="space-y-2 text-center">
                <p className="text-sm text-muted">PDF documents open in your browser&apos;s own viewer.</p>
                <a href={`/api/v1/files/${f.id}`} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center rounded-lg bg-brand-600 px-5 text-sm font-semibold text-white hover:bg-brand-700">Open the PDF</a>
              </div>
            ) : (
              <p className="text-sm text-muted">There is no preview for this kind of file. Use Download to open it.</p>
            )}
          </Card>
          <Card>
            <h2 className="mb-2 text-base font-semibold">About this document</h2>
            <dl className="grid grid-cols-1 gap-x-4 gap-y-2 text-sm sm:grid-cols-2">
              <Item label="Attached to">{href ? <Link href={href} className="text-brand-700 hover:underline">{rule?.label ?? f.resourceType}</Link> : (rule?.label ?? 'Business')}</Item>
              <Item label="Uploaded by">{f.uploadedByName ?? (f.source === 'GENERATED' ? 'TFME Auto' : '—')}</Item>
              <Item label="Added">{when(f.createdAt)}</Item>
              <Item label="Version">{f.version}</Item>
              <Item label="Safety check">{SCAN[f.scanStatus] ?? f.scanStatus}</Item>
              {f.isFinancial && f.retainUntil && <Item label="Kept until">{formatDate(f.retainUntil, ctx.business.timezone, ctx.business.locale)} (financial records cannot be permanently deleted before this)</Item>}
              {f.description && <Item label="Description">{f.description}</Item>}
            </dl>
          </Card>
          {d.versions.length > 1 && (
            <Card>
              <h2 className="mb-2 text-base font-semibold">Version history</h2>
              <ul className="divide-y divide-line text-sm">
                {d.versions.map((v) => (
                  <li key={v.id} className="flex items-center justify-between gap-2 py-2">
                    <span className="min-w-0 truncate">{v.id === f.id ? <strong>Version {v.version}</strong> : <Link href={`/documents/${v.id}`} className="text-brand-700 hover:underline">Version {v.version}</Link>}{v.isCurrent ? ' (current)' : ''} · {formatBytes(v.sizeBytes)}</span>
                    <span className="shrink-0 text-xs text-muted">{formatDate(v.createdAt, ctx.business.timezone, ctx.business.locale)}</span>
                  </li>
                ))}
              </ul>
            </Card>
          )}
        </div>
        <Card>
          <DocumentActions
            id={f.id} name={f.name} displayName={f.displayName} description={f.description} category={f.category} visibility={f.visibility} status={f.status} categories={cats}
            can={{ download: d.can.download, edit: d.can.edit, delete: d.can.delete, share: d.can.share, purge: can('document.purge'), upload: can('document.upload'), restricted: can('document.view_restricted') }}
            locked={f.isFinancial} generated={f.source === 'GENERATED'} shareable={!f.resourceType || !!rule?.customerShareable} writable={ctx.subscription.canWrite}
          />
        </Card>
      </div>
    </>
  );
}

function Item({ label, children }: { label: string; children: React.ReactNode }) {
  return <div><dt className="text-xs uppercase tracking-wide text-muted">{label}</dt><dd className="font-medium">{children || '—'}</dd></div>;
}
