import type { Db, Prisma } from '@/server/db/client';
import type { RequestMeta } from '@/server/context';

/** Canonical audit action names. Add new ones here so they stay greppable. */
export const AuditActions = {
  accountCreated: 'account.created',
  emailVerified: 'account.email_verified',
  loginSucceeded: 'auth.login',
  loginFailed: 'auth.login_failed',
  loginLocked: 'auth.login_locked',
  logout: 'auth.logout',
  passwordChanged: 'auth.password_changed',
  passwordResetRequested: 'auth.password_reset_requested',
  passwordResetCompleted: 'auth.password_reset_completed',
  sessionsRevoked: 'auth.sessions_revoked',
  businessCreated: 'business.created',
  businessSettingsChanged: 'business.settings_changed',
  businessSwitched: 'business.switched',
  memberInvited: 'member.invited',
  memberInviteRevoked: 'member.invite_revoked',
  memberJoined: 'member.joined',
  memberRoleChanged: 'member.role_changed',
  memberSuspended: 'member.suspended',
  memberReactivated: 'member.reactivated',
  memberRemoved: 'member.removed',
  customerCreated: 'customer.created',
  customerUpdated: 'customer.updated',
  customerArchived: 'customer.archived',
  customerRestored: 'customer.restored',
  fileUploaded: 'file.uploaded',
  fileArchived: 'file.archived',
  fileDownloaded: 'file.downloaded',
  fileEdited: 'file.edited',
  fileVisibilityChanged: 'file.visibility_changed',
  fileRestored: 'file.restored',
  fileTrashed: 'file.trashed',
  filePurged: 'file.purged',
  fileVersioned: 'file.versioned',
  fileScanFlagged: 'file.scan_flagged',
  documentGenerated: 'document.generated',
  documentGenerationFailed: 'document.generation_failed',
  documentCategoryChanged: 'document.category_changed',
  documentSettingsChanged: 'document.settings_changed',
  documentCleanup: 'document.cleanup',
  communicationQueued: 'communication.queued',
  communicationSent: 'communication.sent',
  communicationFailed: 'communication.failed',
  communicationSentManually: 'communication.sent_manually',
  communicationRetried: 'communication.retried',
  communicationCancelled: 'communication.cancelled',
  templateChanged: 'communication.template_changed',
  commSettingsChanged: 'communication.settings_changed',
  commPreferenceChanged: 'communication.preference_changed',
  serviceReminderSent: 'service_reminder.sent',
  dataExported: 'data.exported',
  subscriptionChanged: 'subscription.changed',
  paymentReceived: 'billing.payment_received',
  // account & security
  profileUpdated: 'account.profile_updated',
  photoChanged: 'account.photo_changed',
  notificationPrefsChanged: 'account.notification_preferences_changed',
  emailChangeRequested: 'account.email_change_requested',
  emailChanged: 'account.email_changed',
  accountDeactivated: 'account.deactivated',
  sessionRevoked: 'auth.session_revoked',
  mfaEnabled: 'auth.mfa_enabled',
  mfaDisabled: 'auth.mfa_disabled',
  mfaRecoveryCodesRegenerated: 'auth.mfa_recovery_codes_regenerated',
  mfaChallengeFailed: 'auth.mfa_challenge_failed',
  mfaRecoveryCodeUsed: 'auth.mfa_recovery_code_used',
  reauthFailed: 'auth.reauth_failed',
  // business & team
  memberInviteResent: 'member.invite_resent',
  roleCreated: 'role.created',
  rolePermissionsChanged: 'role.permissions_changed',
  roleArchived: 'role.archived',
  ownershipTransferred: 'business.ownership_transferred',
  businessClosed: 'business.closed',
  businessMfaRequirementChanged: 'business.mfa_requirement_changed',
  locationCreated: 'location.created',
  locationUpdated: 'location.updated',
  locationArchived: 'location.archived',
  // billing
  trialStarted: 'subscription.trial_started',
  trialExpired: 'subscription.trial_expired',
  checkoutStarted: 'subscription.checkout_started',
  paymentFailed: 'billing.payment_failed',
  invoiceIssued: 'billing.invoice_issued',
  planChanged: 'subscription.plan_changed',
  downgradeScheduled: 'subscription.downgrade_scheduled',
  downgradeCancelled: 'subscription.downgrade_cancelled',
  subscriptionCancelled: 'subscription.cancelled',
  subscriptionPastDue: 'subscription.past_due',
  subscriptionGrace: 'subscription.grace_period_started',
  subscriptionSuspended: 'subscription.suspended',
  subscriptionExpired: 'subscription.expired',
  platformCustomPlan: 'platform.custom_plan_assigned',
  // workshop operations
  customerStatusChanged: 'customer.status_changed',
  vehicleCreated: 'vehicle.created',
  vehicleUpdated: 'vehicle.updated',
  vehicleArchived: 'vehicle.archived',
  vehicleRestored: 'vehicle.restored',
  vehicleStatusChanged: 'vehicle.status_changed',
  mileageRecorded: 'vehicle.mileage_recorded',
  mileageCorrected: 'vehicle.mileage_corrected',
  bookingCreated: 'booking.created',
  bookingUpdated: 'booking.updated',
  bookingRescheduled: 'booking.rescheduled',
  bookingCancelled: 'booking.cancelled',
  bookingStatusChanged: 'booking.status_changed',
  bookingCheckedIn: 'booking.checked_in',
  bookingNoShow: 'booking.no_show',
  waitingListAdded: 'waiting_list.added',
  waitingListBooked: 'waiting_list.booked',
  waitingListCancelled: 'waiting_list.cancelled',
  recurringCreated: 'booking.recurring_created',
  recurringCancelled: 'booking.recurring_cancelled',
  jobCreated: 'job.created',
  jobUpdated: 'job.updated',
  jobStatusChanged: 'job.status_changed',
  jobStatusOverridden: 'job.status_overridden',
  jobPriorityChanged: 'job.priority_changed',
  jobTechnicianAssigned: 'job.technician_assigned',
  jobCheckedIn: 'job.checked_in',
  inspectionStarted: 'inspection.started',
  inspectionUpdated: 'inspection.updated',
  inspectionCompleted: 'inspection.completed',
  diagnosisRecorded: 'diagnosis.recorded',
  diagnosisUpdated: 'diagnosis.updated',
  diagnosisConfirmed: 'diagnosis.confirmed',
  recommendedWorkChanged: 'recommended_work.changed',
  recommendedWorkDecision: 'recommended_work.decision',
  qualityCheckRecorded: 'job.quality_check',
  jobNoteAdded: 'job.note_added',
  jobNoteVisibilityChanged: 'job.note_visibility_changed',
  jobPhotoAdded: 'job.photo_added',
  jobPhotoVisibilityChanged: 'job.photo_visibility_changed',
  jobPhotoRemoved: 'job.photo_removed',
  jobPartChanged: 'job.part_changed',
  jobLabourChanged: 'job.labour_changed',
  serviceTypeChanged: 'workshop.service_type_changed',
  bayChanged: 'workshop.bay_changed',
  workshopSettingsChanged: 'workshop.settings_changed',
  workshopHoursChanged: 'workshop.hours_changed',
  technicianScheduleChanged: 'workshop.technician_schedule_changed',
  technicianTimeOffChanged: 'workshop.technician_time_off_changed',
  // finance
  quoteCreated: 'quote.created',
  quoteUpdated: 'quote.updated',
  quoteVersionCreated: 'quote.version_created',
  quoteSent: 'quote.sent',
  quoteViewed: 'quote.viewed',
  quoteApproved: 'quote.approved',
  quoteDeclined: 'quote.declined',
  quoteChangesRequested: 'quote.changes_requested',
  quoteExpired: 'quote.expired',
  quoteCancelled: 'quote.cancelled',
  quoteJobCreated: 'quote.job_created',
  quoteConvertedToInvoice: 'quote.converted_to_invoice',
  invoiceCreated: 'invoice.created',
  invoiceUpdated: 'invoice.updated',
  invoiceFinalised: 'invoice.finalised',
  invoiceSent: 'invoice.sent',
  invoiceViewed: 'invoice.viewed',
  invoiceCancelled: 'invoice.cancelled',
  invoiceWrittenOff: 'invoice.written_off',
  invoiceOverdue: 'invoice.overdue',
  paymentRecorded: 'payment.recorded',
  paymentCompleted: 'payment.completed',
  paymentFailed2: 'payment.failed',
  paymentCancelled: 'payment.cancelled',
  paymentRefunded: 'payment.refunded',
  paymentReconciled: 'payment.reconciled',
  paymentOnlineStarted: 'payment.online_started',
  customerCreditAdded: 'credit.added',
  customerCreditApplied: 'credit.applied',
  creditNoteCreated: 'credit_note.created',
  creditNoteIssued: 'credit_note.issued',
  creditNoteCancelled: 'credit_note.cancelled',
  receiptIssued: 'receipt.issued',
  financeSettingsChanged: 'finance.settings_changed',
  financeExported: 'finance.exported',
  statementGenerated: 'statement.generated',
  reminderQueued: 'invoice.reminder_queued',
  labourCostRateChanged: 'finance.labour_cost_rate_changed',
  // inventory
  partCreated: 'part.created',
  partUpdated: 'part.updated',
  partArchived: 'part.archived',
  partRestored: 'part.restored',
  partPriceChanged: 'part.price_changed',
  partSupplierChanged: 'part.supplier_changed',
  partCompatibilityChanged: 'part.compatibility_changed',
  partCategoryCreated: 'part_category.created',
  partCategoryUpdated: 'part_category.updated',
  partCategoryArchived: 'part_category.archived',
  partsBulkUpdated: 'parts.bulk_updated',
  partsImported: 'parts.imported',
  inventorySettingsChanged: 'inventory.settings_changed',
  stockReceived: 'stock.received',
  stockReserved: 'stock.reserved',
  stockUnreserved: 'stock.unreserved',
  stockUsed: 'stock.used',
  stockSold: 'stock.sold',
  stockReturned: 'stock.returned',
  stockAdjusted: 'stock.adjusted',
  stockDamaged: 'stock.damaged',
  stockLost: 'stock.lost',
  stockWentNegative: 'stock.went_negative',
  stockLocationChanged: 'stock.location_changed',
  stockExported: 'inventory.exported',
  supplierCreated: 'supplier.created',
  supplierUpdated: 'supplier.updated',
  supplierArchived: 'supplier.archived',
  purchaseOrderCreated: 'purchase_order.created',
  purchaseOrderUpdated: 'purchase_order.updated',
  purchaseOrderSubmitted: 'purchase_order.submitted',
  purchaseOrderApproved: 'purchase_order.approved',
  purchaseOrderRejected: 'purchase_order.rejected',
  purchaseOrderOrdered: 'purchase_order.ordered',
  purchaseOrderSent: 'purchase_order.sent',
  purchaseOrderPartiallyReceived: 'purchase_order.partially_received',
  purchaseOrderReceived: 'purchase_order.received',
  purchaseOrderClosedShort: 'purchase_order.closed_short',
  purchaseOrderCancelled: 'purchase_order.cancelled',
  supplierReturnCreated: 'supplier_return.created',
  transferCreated: 'stock_transfer.created',
  transferRequested: 'stock_transfer.requested',
  transferApproved: 'stock_transfer.approved',
  transferShipped: 'stock_transfer.shipped',
  transferReceived: 'stock_transfer.received',
  transferCancelled: 'stock_transfer.cancelled',
  // team
  technicianSettingsChanged: 'technician.settings_changed',
  technicianDeactivated: 'technician.deactivated',
  technicianReactivated: 'technician.reactivated',
  labourRateChanged: 'labour.rate_changed',
  memberLocationsChanged: 'member.locations_changed',
  jobAssignmentChanged: 'job.assignment_changed',
  timeEntryStarted: 'time_entry.started',
  timeEntryStopped: 'time_entry.stopped',
  timeEntryCreated: 'time_entry.created',
  timeEntryEdited: 'time_entry.edited',
  timeEntryVoided: 'time_entry.voided',
  timeEntryApproved: 'time_entry.approved',
  timeEntryPosted: 'time_entry.posted_to_labour',
  teamExported: 'team.exported',
  // data
  exportRequested: 'data.export_requested',
  exportDownloaded: 'data.export_downloaded',
  // Part 7: reports, settings, imports, administration
  reportExported: 'report.exported',
  reportSaved: 'report.saved',
  reportUpdated: 'report.updated',
  reportArchived: 'report.archived',
  reportScheduled: 'report.scheduled',
  reportScheduleChanged: 'report.schedule_changed',
  reportDelivered: 'report.delivered',
  reportDeliveryFailed: 'report.delivery_failed',
  configChanged: 'config.changed',
  numberingChanged: 'config.numbering_changed',
  labourSettingsChanged: 'config.labour_changed',
  jobConfigChanged: 'config.jobs_changed',
  vehicleConfigChanged: 'config.vehicles_changed',
  inventoryConfigChanged: 'config.inventory_changed',
  reportingSettingsChanged: 'config.reporting_changed',
  securitySettingsChanged: 'config.security_changed',
  retentionSettingsChanged: 'config.retention_changed',
  bookingRulesChanged: 'config.booking_rules_changed',
  serviceCatalogueChanged: 'config.service_changed',
  jobTemplateChanged: 'config.job_template_changed',
  locationChanged: 'location.changed',
  importUploaded: 'import.uploaded',
  importValidated: 'import.validated',
  importCompleted: 'import.completed',
  importFailed: 'import.failed',
  importCancelled: 'import.cancelled',
  recordRestored: 'archive.restored',
  auditExported: 'audit.exported',
} as const;

export interface AuditEvent {
  action: string;
  businessId?: string | null;
  userId?: string | null;
  resourceType?: string;
  resourceId?: string;
  metadata?: Record<string, unknown>;
  before?: unknown;
  after?: unknown;
}

const SENSITIVE_KEYS = new Set([
  'passwordHash', 'password', 'token', 'tokenHash', 'inviteTokenHash', 'secret', 'providerSubscriptionRef',
]);

/** Strip secrets from before/after snapshots and make them JSON-safe. */
export function sanitizeForAudit(value: unknown): Prisma.InputJsonValue | undefined {
  if (value === undefined || value === null) return undefined;
  const json = JSON.parse(
    JSON.stringify(value, (k, v) => (SENSITIVE_KEYS.has(k) ? '[redacted]' : v)),
  ) as Prisma.InputJsonValue;
  return json;
}

/**
 * Append an audit event. Pass the surrounding transaction (`db`) so the audit
 * record commits atomically with the change it describes.
 *
 * Uses createMany (INSERT without RETURNING): the audit table's row-level
 * security allows tenant-less inserts but only tenants can SELECT their rows.
 */
export async function recordAudit(db: Db, meta: RequestMeta | undefined, e: AuditEvent): Promise<void> {
  await db.auditLog.createMany({
    data: [
      {
        action: e.action,
        businessId: e.businessId ?? null,
        userId: e.userId ?? null,
        resourceType: e.resourceType ?? null,
        resourceId: e.resourceId ?? null,
        metadata: sanitizeForAudit(e.metadata) ?? undefined,
        before: sanitizeForAudit(e.before) ?? undefined,
        after: sanitizeForAudit(e.after) ?? undefined,
        ip: meta?.ip ?? null,
        userAgent: meta?.userAgent?.slice(0, 300) ?? null,
        requestId: meta?.requestId ?? null,
      },
    ],
  });
}
